# Generated by Django 4.2.4 on 2023-10-01 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cat_p",
            table="cat_P",
        ),
    ]
