# Generated by Django 4.2.4 on 2023-10-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_cat_p_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat_p",
            name="descripcion",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="cat_p",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="ges_P",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("descripcion", models.CharField(max_length=100)),
                ("precio", models.IntegerField()),
                ("img", models.ImageField(unique=True, upload_to="productos")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.cat_p"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "ges_P",
            },
        ),
    ]
