# Generated by Django 4.2.4 on 2023-10-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_cat_p_descripcion_alter_cat_p_name_ges_p"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ges_p",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="productos"),
        ),
    ]
