# Generated by Django 4.2.4 on 2023-10-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_ges_p_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ges_p",
            name="img",
            field=models.ImageField(blank=True, default=1, upload_to="productos"),
            preserve_default=False,
        ),
    ]
