# Generated by Django 4.2.4 on 2023-10-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_ges_p_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opinion", models.TextField()),
                (
                    "calificacion",
                    models.DecimalField(
                        choices=[
                            (1, "1 estrella"),
                            (1.5, "1.5 estrellas"),
                            (2, "2 estrellas"),
                            (2.5, "2.5 estrellas"),
                            (3, "3 estrellas"),
                            (3.5, "3.5 estrellas"),
                            (4, "4 estrellas"),
                            (4.5, "4.5 estrellas"),
                            (5, "5 estrellas"),
                        ],
                        decimal_places=1,
                        default=1.0,
                        max_digits=3,
                    ),
                ),
                (
                    "nameP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.ges_p"
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "review",
            },
        ),
    ]
