# Generated by Django 4.2.4 on 2023-10-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat_p",
            name="descripcion",
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
