# Generated by Django 4.2.4 on 2023-10-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_cat_p_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ges_p",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
